---
collections:
  - name: community.general
  - name: ansible.posix
  - name: ansible.netcommon
  - name: community.postgresql
  - name: community.mysql
  - name: community.aws
  - name: amazon.aws
  - name: azure.azcollection
  - name: middleware_automation.infinispan
    src: https://github.com/ansible-middleware/infinispan
  - name: middleware_automation.keycloak
    version: "==1.0.6"
  - name: middleware_automation.wildfly
    src: https://github.com/ansible-middleware/wildfly
    version: "==1.0.5"
  - name: middleware_automation.amq
    src: https://github.com/ansible-middleware/amq
  - name: middleware_automation.jws
    version: "==1.1.1"
  - name: middleware_automation.redhat_csp_download
    version: "==1.2.2"
  - name: middleware_automation.jcliff
    version: "==0.0.23"
