---
collections:
  - name: community.general
  - name: ansible.posix
  - name: ansible.netcommon
  - name: community.postgresql
  - name: community.mysql
  - name: community.aws
  - name: amazon.aws
  - name: azure.azcollection
  - name: google.cloud
  - name: middleware_automation.infinispan
    source: https://github.com/ansible-middleware/infinispan
    type: git
  - name: middleware_automation.keycloak
    source: https://github.com/ansible-middleware/keycloak
    type: git
  - name: middleware_automation.wildfly
    source: https://github.com/ansible-middleware/wildfly
    type: git
  - name: middleware_automation.amq
    source: https://github.com/ansible-middleware/amq.git
    type: git
  - name: middleware_automation.jws
    version: "==1.1.1"
  - name: middleware_automation.redhat_csp_download
    version: "==1.2.2"
  - name: middleware_automation.jcliff
    version: "==0.0.23"
